service: McCount

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

# functions:
#   hello:
#     handler: handler.hello

resources:
  Resources:
    ServerData:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${sls:stage}-MCServerData
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
