service: McCount

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

# functions:
#   hello:
#     handler: handler.hello

resources:
  Resources:
    ServerData:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${sls:stage}-MCServerData
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH

    ServerTimeseries:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${sls:stage}-MCServerTimeseries
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: n # Name
            AttributeType: S
          - AttributeName: t # Timestamp
            AttributeType: N
        KeySchema:
          - AttributeName: n
            KeyType: HASH
          - AttributeName: t
            KeyType: RANGE

    ServerPlayerCountQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${sls:stage}-MCServerPollQueue
        MessageRetentionPeriod: 86400