service: McCount

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  environment:
    TIMESERIES_TABLE_NAME: ${sls:stage}-MCServerTimeseries
    SERVER_REQUESTS_TABLE_NAME: ${sls:stage}-MCServerRequests

plugins:
  - serverless-iam-roles-per-function

functions:
  ping:
    handler: src/functions/pinger.ping
    memorySize: 128
    timeout: 30
    events:
      - http:
          path: ping
          method: get
          cors:
            origin: '*'
            headers: '*'

  fetchTimeSeries:
    handler: src/functions/timeSeries.fetchTimeSeries
    memorySize: 128
    timeout: 15
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${sls:stage}-MCServerTimeseries
    events:
      - http:
          path: timeseries
          method: get
          cors:
            origin: '*'
            headers: '*'

  createServerRequest:
    handler: src/functions/serverRequests.createServerRequest
    memorySize: 128
    timeout: 15
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
          - dynamodb:PutItem
        Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${sls:stage}-MCServerRequests
    events:
      - http:
          path: server-requests
          method: post
          cors:
            origin: '*'
            headers: '*'

  pingAndSave:
    handler: src/functions/pinger.pingAndSave
    memorySize: 128
    timeout: 90
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
          - dynamodb:PutItem
        Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${sls:stage}-MCServerTimeseries
    events:
      - sqs:
          arn: arn:aws:sqs:${aws:region}:${aws:accountId}:${sls:stage}-MCServerPollQueue

resources:
  Resources:
    ServerData:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${sls:stage}-MCServerData
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH

    ServerRequest:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${sls:stage}-MCServerRequests
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH

    ServerTimeseries:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${sls:stage}-MCServerTimeseries
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: n
            AttributeType: S
          - AttributeName: t
            AttributeType: N
        KeySchema:
          - AttributeName: n
            KeyType: HASH
          - AttributeName: t
            KeyType: RANGE

    ServerPlayerCountQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${sls:stage}-MCServerPollQueue
        MessageRetentionPeriod: 86400
        VisibilityTimeout: 90